@startuml image
entity "image" {
  *image_id[PK] : 画像ID : BIGINT
  --
  file_path : ファイルパス : VARCHAR(255)
  unique_filename : ユニークファイル名 : VARCHAR(255)
  original_filename : オリジナルファイル名 : VARCHAR(255)
}
@enduml