@startuml post
entity "post" {
  *post_id[PK] : 投稿ID : BIGINT
  --
  status : ステータス : VARCHAR(20)
  caption : キャプション : TEXT
  location : 撮影場所 : VARCHAR(255)
  post_date : アップロード日 : DATE
  post_datetime : アップロード日時 : DATETIME
  delete_password : 削除用パスワード : VARCHAR(255)
}
@enduml